- .asf.yaml
fix GH-81
https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Deletebranchonmerge
> Add this snippet below so branches get auto-deleted upon PR merge to
> your default branch:
>
> Delete Branch on Merge
>
>     github:
>       del_branch_on_merge: true
> GH-81: Enable delete branch on merge

- .editorconfig
- .env
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .gitmodules
- .pre-commit-config.yaml
- ci/scripts/build.sh
- ci/scripts/test.sh
Fix GH-11
This part:
https://github.com/apache/arrow/blob/58415d1fac50cb829b3dcf08526033d6db8c30db/.github/workflows/go.yml#L305-L360
This also imports `ci/scripts/go_{build,test}.sh` from apache/arrow.
This also introduce ShellCheck and shfmt with pre-commit.
This also adds apache/arrow-testing and apache/parquet-testing submodules.
> GH-11: Add test CI: macOS

- .github/dependabot.yml
Fix GH-2
We only need this part:
https://github.com/apache/arrow/blob/58415d1fac50cb829b3dcf08526033d6db8c30db/.github/dependabot.yml#L18-L33
> GH-2: Enable Dependabot

- .github/workflows/test.yml
- .golangci.yaml
- .pre-commit-config.yaml
- arrow/flight/flightsql/server.go
- arrow/internal/flight_integration/scenario.go
- ci/scripts/test.sh
Fix GH-15
Related parts:
* https://github.com/apache/arrow/blob/58415d1fac50cb829b3dcf08526033d6db8c30db/.pre-commit-config.yaml#L151-L164
* https://github.com/apache/arrow/blob/main/.golangci.yaml
staticcheck is also used via golangci. We need to use "nolint:staticcheck,XXX" instead of "lint:ignore XXX" for it.
See also: https://golangci-lint.run/usage/false-positives/#nolint
> GH-15: Enable linter

- .github/workflows/lint.yml
- .github/workflows/test.yml
It seems that Dependabot always use `dependabot/*` branch. If we ignore `push` trigger for the branch, we can run only `pull_request` trigger for Dependabot.
> GH-100: Don't run CI jobs by Dependabot push

- .dockerallow
- .env
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .golangci.yaml
- .pre-commit-config.yaml
- ci/docker/debian-12.dockerfile
- ci/scripts/test.sh
- compose.yaml
Fix GH-5
This part: https://github.com/apache/arrow/blob/58415d1fac50cb829b3dcf08526033d6db8c30db/.github/workflows/go.yml#L49-L135
> GH-5: Add test CI: Docker based

- .gitignore
- .pre-commit-config.yaml
- dev/release/check_rat_report.py
- dev/release/rat_exclude_files.txt
- dev/release/run_rat.sh
Fix GH-16
Apache Rat: https://creadur.apache.org/rat/
It's a release audit tool.
Related files:
* https://github.com/apache/arrow/blob/main/dev/release/run-rat.sh
* https://github.com/apache/arrow/blob/main/dev/release/rat_exclude_files.txt
> GH-16: Add Apache Rat CI

- .github/workflows/test.yml
- ci/scripts/msys2_setup.sh
Fix https://github.com/apache/arrow-go/issues/13
This part: https://github.com/apache/arrow/blob/58415d1fac50cb829b3dcf08526033d6db8c30db/.github/workflows/go.yml#L404-L465
> GH-13: Add test CI: Windows + MinGW

- .github/workflows/test.yml
Fix https://github.com/apache/arrow-go/issues/107
We have some jobs that run on ARM self-hosted runners, we should also add those: https://github.com/apache/arrow/blob/main/.github/workflows/go.yml#L80-L91
> GH-107: Add test CI for arm Runners

- .github/workflows/test.yml
Looks like some of the test runs (particularly the ARM runs) are close to the 15 minute timeout and end up occasionally being flaky and failing. Let's bump the timeout to 20 minutes just in case so that we aren't skating the edge anymore.
> MINOR: Bump CI test timeouts

- .github/workflows/lint.yml
- .github/workflows/rc.yml
- .github/workflows/test.yml
- .gitignore
- arrow/doc.go
- ci/scripts/build.sh
- dev/release/README.md
- dev/release/release.sh
- dev/release/release_rc.sh
- dev/release/verify_rc.sh
Fix GH-21
This is based on
https://github.com/apache/arrow-julia/tree/main/dev/release and https://github.com/apache/arrow-adbc/tree/main/dev/release .
Workflow:
Cut a RC:
1. Update `PkgVersion` in `arrow/doc.go`
2. Run `dev/release/release_rc.sh`
1. `dev/release/release_rc.sh` pushes `v${version}-rc${rc}` tag
2. `.github/workflows/rc.yml` creates `apache-arrow-go-${version}.tar.gz{,.sha256,.sha512}`
3. `.github/workflows/rc.yml` uploads `apache-arrow-go-${version}.tar.gz{,.sha256,.sha512}` to GitHub Releases
4. `dev/release/release_rc.sh` downloads `apache-arrow-go-${version}.tar.gz` from GitHub Releases
5. `dev/release/release_rc.sh` signs `apache-arrow-go-${version}.tar.gz` as `apache-arrow-go-${version}.tar.gz.asc`
6. `dev/release/release_rc.sh` uploads …
> GH-21: Add release CI

- .github/workflows/test.yml
Fix GH-131
It's not available on forks.
> GH-131: Don't use self-hosted arm runner on forks

- .github/workflows/test.yml
> GH-17: Add integration test CI

- .github/workflows/test.yml
Fix GH-140
Use macOS 14 instead.
> GH-140: Drop support for macOS 12

- .asf.yaml
Fix #139 
The asf-site content will be deployed to https://arrow.apache.org/go/ automatically.
I have created an empty `asf-site` branch and pushed it.
We have to add an index.html there pointing to `https://pkg.go.dev/github.com/apache/arrow-go/v${VERSION}`.
> GH-139: Add config to publish asf-site branch to go subdir

- .github/CODEOWNERS
Adding initial CODEOWNERS file
tagging relevant people to review. If any of you don't want to be listed on the CODEOWNERS just comment here and I'll take you off.
Fixes #26
> GH-26: Add Codeowners

- arrow/array/string.go
- arrow/array/string_test.go
- arrow/ipc/writer.go
- parquet/metadata/statistics_types.gen.go
Fixes #41 
Makes the behavior of `ValueOffset` consistent between String and Binary arrays.
> GH-41: [Array] Make String and Binary consistent

- arrow/compute/cast_test.go
- arrow/compute/executor.go
> fix(arrow/compute): fix scenario where prealloc output is missed

- arrow/compute/internal/kernels/cast_numeric_neon_arm64.s
- arrow/internal/testing/tools/fpunwind.go
- arrow/internal/testing/tools/fpunwind_arm64.s
- arrow/internal/testing/tools/fpunwind_default.go
- arrow/math/int64_neon_arm64.s
- arrow/math/uint64_neon_arm64.s
- arrow/memory/memory_neon_arm64.s
- arrow/memory/memory_test.go
- internal/utils/min_max_neon_arm64.s
- parquet/internal/bmi/bitmap_neon_arm64.s
- parquet/internal/utils/bit_packing_neon_arm64.s
- parquet/internal/utils/unpack_bool_neon_arm64.s
The arm64 neon assembly functions in this repository overwrite the frame
pointer saved by their callers, leading to crashes from the Go runtime
execution tracer and profilers which use frame pointer unwinding. For
historical reasons, on arm64 Go functions save the caller's frame
pointer register (x29) one word below their stack frame. See
go.dev/s/regabi#arm64-architecture. The assembly functions here,
translated from C compiler output, save values at the top of their
frame, and overwrite the frame pointer saved by the caller. We can fix
this by decrementing the stack pointer past where that frame pointer is
saved before saving anything on the stack.
Fixed with this sed script on my macos laptop + manual cleanup to match
indentation:
```
/stp[\t ]*x29/i\
// The Go ABI saves the frame …
```
> fix: don't clobber saved frame pointer in arm64 assembly functions

- arrow/extensions/extensions.go
- parquet/pqarrow/encode_arrow_test.go
- parquet/pqarrow/schema.go
Split from #171 to be a more focused PR.
Currently we will properly write arrow data with the canonical UUID extension type as a parquet UUID column via `pqarrow`. This PR enables us to read back that data using the `extensions.UUID` data type correctly even when we don't have a stored schema.
Added a test to the `ArrowExtensionTypeRoundTrip` to ensure proper round trip without a stored schema.
> fix(parquet): Reading UUID columns

- arrow/compute/exprs/exec.go
- arrow/compute/exprs/exec_test.go
- arrow/compute/exprs/extension_types.go
- arrow/compute/scalar_compare.go
- arrow/compute/scalar_compare_test.go
- arrow/compute/utils.go
- arrow/extensions/uuid.go
Split from #171 
Enable using the comparison kernels (equal, less, less_equal, greater, greater_equal) with UUID columns and extension types in general.
Tests are added to check the kernel dispatch and to ensure compute via substrait works for UUID type scalars.
> fix(arrow/compute): compare kernels with UUID

- .github/pull_request_template.md
- dev/release/rat_exclude_files.txt
> GH-23: Add PR template

- arrow/compute/exprs/types.go
- arrow/compute/internal/kernels/scalar_boolean.go
- arrow/compute/scalar_bool.go
- arrow/compute/scalar_bool_test.go
Adding implementation and tests for a "not" function to the compute package.
> feat(arrow/compute): Implement kernel for "not" function

- arrow/cdata/cdata_exports.go
- arrow/cdata/cdata_test.go
- arrow/cdata/cdata_test_framework.go
Fixes #172 
Includes a test that reproduced the original reported issue
> fix(arrow/cdata): handle export struct with no fields

- arrow/compute/internal/kernels/scalar_comparisons.go
- arrow/compute/scalar_compare.go
- arrow/compute/scalar_compare_test.go
Currently the `is_nan` compute kernel is a `MetaFunction` which cannot be dispatched via kernel dispatch making it only usable via calling it directly with `CallFunction`. By shifting it to be a proper function instead of a `MetaFunction` this improves its compatibility and makes it able to be dispatched and thus called through the substrait interface in the `exprs` package.
> feat(arrow/compute): make is_nan dispatchable

- CONTRIBUTING.md
> GH-20: Add CONTRIBUTING.md

- arrow/cdata/arrow/c/abi.h
- arrow/cdata/arrow/c/helpers.h
- arrow/cdata/cdata.go
- arrow/cdata/cdata_exports.go
- arrow/cdata/cdata_test.go
- arrow/cdata/cdata_test_framework.go
- arrow/cdata/exports.go
- arrow/cdata/interface.go
- arrow/cdata/trampoline.c
This adds a basic implementation of helpers for managing an ArrowAsyncDeviceStreamHandler for using the Async Arrow C Device interface. The corresponding C++ helper implementation can be found at https://github.com/apache/arrow/pull/44495 with the discusson on the actual C structures located at https://github.com/apache/arrow/pull/43632.
> feat(arrow/cdata): Add Implementation of Async C Data interface

- .github/workflows/test.yml
- ci/scripts/test.sh
See https://github.com/apache/arrow/pull/44798
Fixing the CI for macOS by switching to pkgconf from deprecated pkg-config for Homebrew
> ci: update pkg-config to pkgconf on Homebrew

- .github/workflows/comment_bot.yml
The syntax for permissions should use `contents` instead of `content`, see: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions
Update to correct GitHub actions syntax.
No, but can be seen the usage on the Arrow repo: https://github.com/apache/arrow/blob/bbda6b1e1322c5a9b8c107a03343d18b759694c1/.github/workflows/comment_bot.yml#L28
No
> ci: use correct GitHub Actions permission "contents" instead of "content"

- internal/json/json.go
- internal/json/json_stdlib.go
Grafana and Grafana plugins both use arrow-go, but do not use arrow's `internal/json`. A decent amount of used heap is initialized by https://github.com/goccy/go-json, so it would be useful to be able to prevent the initialization.
The example below shows that 60% of this heap profile in a Grafana plugin is used by `go-json`'s encoder & decoder packages.
I have submitted a [PR to go-json](https://github.com/goccy/go-json/pull/490) to switch to lazy initialization (additional details in the PR), but I am having a hard time getting a response from the maintainer, so am attempting a different approach to the problem with this PR.
Adds `arrow_json_stdlib` build tag so that it's possible to switch to `encoding/json` and avoid the overhead of https://github.com/goccy/go-json.
I tested this …
> fix(internal/json): add arrow_json_stdlib build tag

- parquet/pqarrow/encode_arrow_test.go
- parquet/pqarrow/file_reader.go
- parquet/pqarrow/properties.go
- parquet/pqarrow/schema.go
closes #195
For parquet files that contain more than 2GB of data in a column, we should allow a user to force using the LargeString/LargeBinary variants without requiring a stored schema.
Adds `ForceLarge` option to `pqarrow.ArrowReadProperties` and enables it to force usage of `LargeString` and `LargeBinary` data types.
Yes, a unit test is added.
No breaking changes, only the addition of a new option.
> feat(parquet/pqarrow): Add ForceLarge option

- parquet/metadata/statistics_test.go
- parquet/metadata/statistics_types.gen.go
- parquet/metadata/statistics_types.gen.go.tmpl
fixes #209 
Fixing `UpdateSpaced` statistics methods to properly check unsigned values to ensure proper handling of default min/max values.
Yes, unit test was added to confirm.
None, other than fixing the reported bug.
> fix(parquet/metadata): fix default unsigned int statistics

- go.mod
- go.sum
A follow up to https://github.com/apache/arrow-go/pull/199#issuecomment-2494887343
> i will continue trying to get the go-json PR merged, and if i do, i'll open another PR to update the dependency here.
Bumps go-json dependency to include changes from https://github.com/goccy/go-json/pull/490
I am assuming CI tests should cover this.
No
> chore: bump github.com/goccy/go-json to v0.10.4

- parquet/file/file_reader.go
- parquet/file/row_group_reader.go
- parquet/metadata/file.go
- parquet/metadata/metadata_test.go
After looking into the code, I found that `footerOffset` is mainly used in parsing the meta data of parquet file.
I think we can store it in `FileMetaData`, so we don't need to get `footerOffset` again when we use `WithMetadata`. 
Move `Reader.footerOffset` into `FileMetadata`
> feat(parquet): Move footerOffset into FileMetaData

- arrow/ipc/file_reader.go
- arrow/ipc/file_writer.go
- arrow/ipc/metadata.go
- arrow/ipc/metadata_test.go
- arrow/ipc/reader.go
- arrow/ipc/reader_test.go
closes #207 
Adding new method `NewMappedFileReader` to ipc package which accepts a byte slice instead of a `ReaderAtSeeker`. Updates `ipcSource` to reference the raw byte slices from the input directly instead of wrapping with `bytes.NewReader` which forces copies via `Read`, `ReadFull`, etc.
Unit tests added to confirm that the pointers match and that we aren't allocating unnecessarily.
Shouldn't be any user-facing changes other than a reduction in memory usage when reading non-compressed IPC data.
> feat(arrow/ipc): implement lazy loading/zero-copy for IPC files

- .htaccess
Fixes GH-202
We need our canonical URL.
Redirect to https://pkg.go.dev/github.com/apache/arrow-go/ .
No.
Yes.
> chore(website): redirect to https://pkg.go.dev/github.com/apache/arrow-go/

- .asf.yaml
Fixes GH-202
We need `.asf.yaml` to publish the `asf-site` branch to https://arrow.apache.org/go/ .
Add `.asf.yaml`.
No.
Yes.
> chore(website): add .asf.yaml

- .asf.yaml
https://arrow.apache.org/go/ is available now. So let's use it instead of https://arrow.apache.org/ .
Closes #233.
Changes the URL in `.asf.yml`.
No.
No.
> chore: Update the project URL in apache/arrow-go

- .github/workflows/test.yml
The Java implementation is split to apache/arrow-java from apache/arrow. So the current integration test doesn't use the Java implementation. 
Closes #238.
Checkout apache/arrow-java.
Yes.
No.
> chore: Enable Java integration test

- arrow/flight/flightsql/column_metadata.go
- parquet/encryption_read_config_test.go
- parquet/encryption_write_config_test.go
- parquet/file/column_writer.go
- parquet/file/column_writer_test.go
- parquet/file/file_reader.go
- parquet/file/file_writer.go
- parquet/file/file_writer_test.go
- parquet/file/page_reader.go
- parquet/file/page_writer.go
- parquet/file/row_group_writer.go
- parquet/file/size_statistics.go
- parquet/internal/encryption/decryptor.go
- parquet/metadata/column_chunk.go
- parquet/metadata/file.go
- parquet/metadata/metadata_test.go
- parquet/metadata/page_index.go
- parquet/metadata/page_index_internal_test.go
- parquet/metadata/page_index_test.go
- parquet/metadata/statistics.go
- parquet/metadata/statistics_types.gen.go
- parquet/metadata/statistics_types.gen.go.tmpl
- parquet/pqarrow/schema.go
- parquet/types.go
- parquet/writer_properties.go
Adds support for writing and retrieving Page Indexes from parquet files
Added new writer properties to enable writing PageIndexes either as default or for specific columns.
Added `RowGroupPageIndexReader`, `ColumnIndexReader`, `OffsetIndexReader` to access page index information.
Yes, extensive unit tests have been added including round trip tests and encryption/decryption tests.
no. Just new functions available.
closes #33
> feat(parquet): Add support for Page Indexes

- dev/release/release.sh
closes #242
We should use
`https://dist.apache.org/repos/dist/release/arrow/apache-arrow-go-${version}` but `https://dist.apache.org/repos/dist/release/arrow` was used. (The last `/apache-arrow-go-${version}` was missing.)
Add missing `apache-arrow-go-${version}` part.
No.
No.
> fix(release): fix wrong upload path

- dev/release/post-website.sh
- dev/release/release.sh
Ease of utility for release process
Fixing `svn add` command to explicitly refer to the directory so it doesn't present an error anymore.
Add script to generate the markdown page for adding release notes to the arrow-site repo.
> fix(release): fix svn add command and add script to generate release notes

- .github/workflows/test.yml
Fixes: #267 
Replaced the running platform from `self-hosted arm` runner to `ubuntu-24.04-arm` 
Not locally, but can be tested by triggering the runner
No
> chore: Update self-hosted arm runner to ubuntu-24.04-arm

- .github/workflows/test.yml
The existing version we are using has been deprecated, we need to upgrade to maintain the stability of our CI
> ci: update actions/cache

- arrow/bitutil/bitmaps.go
Fixes the broken 32-bit arch tests identified by #32 
Defining the `opAligned` pure go fallback methods for bitmap operations.
Yes, it makes the tests succeed properly on `GOARCH=386`
No.
> fix(arrow/bitutil): fix bitmap ops on 32-bit platforms

- parquet/internal/encoding/boolean_decoder.go
- parquet/internal/encoding/byte_array_decoder.go
- parquet/internal/encoding/byte_stream_split.go
- parquet/internal/encoding/decoder.go
- parquet/internal/encoding/delta_bit_packing.go
- parquet/internal/encoding/delta_byte_array.go
- parquet/internal/encoding/delta_length_byte_array.go
- parquet/internal/encoding/encoding_test.go
- parquet/internal/encoding/fixed_len_byte_array_decoder.go
- parquet/internal/encoding/plain_encoder_types.gen.go
- parquet/internal/encoding/plain_encoder_types.gen.go.tmpl
- parquet/internal/encoding/typed_encoder.gen.go
- parquet/internal/encoding/typed_encoder.gen.go.tmpl
- parquet/internal/encoding/types.go
- parquet/internal/utils/bit_reader.go
- parquet/internal/utils/rle.go
Building towards proper support for Skipping rows to address #278 we need to be able to efficiently discard values from decoders rather than actively having to allocate a buffer and read into it. This makes the skipping/seeking within a page more efficient.
Adding a new `Discard` method to the `Decoder` interface along with implementations for all the various decoders
Yes, tests are added for the various decoders.
No, this is in an internal package.
> feat(internal/encoding): add Discard method to decoders

- internal/utils/min_max_avx2_amd64.s
Fixes #279
In all instances where the generated assembly is clobbering the BP register, we insert a frame size so that the Go assembler will insert a save/restore of the BP, preventing the spurious crash discovered in #279
There isn't really a consistent way to easily reproduce in a unit test, but I'm open to suggestions if anyone has one
No
> fix(internal/utils): fix clobbering BP

- internal/utils/buf_reader.go
- parquet/file/column_reader.go
- parquet/file/column_reader_test.go
- parquet/file/column_reader_types.gen.go
- parquet/file/column_reader_types.gen.go.tmpl
- parquet/file/file_reader.go
- parquet/file/file_reader_mmap_windows.go
- parquet/file/page_reader.go
- parquet/file/record_reader.go
- parquet/file/row_group_reader.go
- parquet/internal/testutils/pagebuilder.go
- parquet/metadata/page_index.go
- parquet/reader_properties.go
Addressing the comments in https://github.com/apache/arrow-go/issues/278#issuecomment-2657578697 to allow for optimizing reads by skipping entire pages and leveraging the offset index if it exists.
Deprecating the old `NewColumnChunkReader` and `NewPageReader` methods as they really aren't safe to use outside of the package, and have proved difficult to evolve without breaking changes. Instead users should rely on using the `RowGroupReader` to perform the creation of the column readers and page readers, which is generally what is done by consumers already.
Adding `SeekToRow` method on the ColumnChunkReader to allow skipping to a particular row in the column chunk (which also allows quickly resetting back to the beginning of a column!) along with `SeekToPageWithRow` method on the page …
> feat(parquet/file): Add SeekToRow for Column readers

- arrow/array/compare.go
- arrow/array/compare_test.go
- arrow/array/util.go
Fixes: #56 
Many databases, including PostgreSQL, do not accept null characters (\x00) in strings. This PR introduces `arrayApproxEqualString` & `arrayApproxEqualLargeString`, functions that enables approximate equality comparison for string arrays while ignoring trailing null characters. This helps improve consistency with database behavior and aligns with existing arrayApproxEqualFloat16.
- Added `arrayApproxEqualString`:
- Compares two string arrays for approximate equality.
- Ignores trailing null characters (\x00).
- Added unit tests in `compare_test.go` to verify correctness.
Yes, unit tests have been added to validate:
- Identical strings return true.
- Strings differing only in trailing null characters return true.
- Completely different strings return false.
No
> feat: Add arrayApproxEqualString to handle null characters in string.

- internal/utils/buf_reader.go
- parquet/file/column_writer_test.go
- parquet/file/file_reader_test.go
- parquet/file/page_reader.go
- parquet/reader_properties.go
When we create a reader with `BufferedStreamEnabled = false`, we have to first create a `data` slice. 
https://github.com/apache/arrow-go/blob/efecae3596e6734ce8244a5ed1befdcff09884df/parquet/reader_properties.go#L76-L91
And we will create another slice with same size in the `NewBufferedReader` again, which is redundant.
https://github.com/apache/arrow-go/blob/efecae3596e6734ce8244a5ed1befdcff09884df/internal/utils/buf_reader.go#L45-L51
- Add a new struct `byteReader`, which is a wrapper of `bytes.NewReader` and implement `BufferedReader` interface.
- Remove `BufferSize()` method from `BufferedReader` interface
`BufferedReader` created from `bytes.NewReader` in tests are all replaced by new function `NewByteReader`.
No.
> feat(parquet): add byte buffer when disable buffered stream

- parquet/encryption_read_config_test.go
- parquet/encryption_write_config_test.go
As a result of https://github.com/apache/arrow/issues/45073, the test files in the parquet-testing repo were updated (https://github.com/apache/parquet-testing/pull/65). 
This led to having to also update the corresponding tests here too similar to https://github.com/apache/arrow/pull/45074
> chore(testing): Update testing submodules

- arrow/array/record.go
- arrow/array/record_test.go
With the advent of Go iterators via the [iter](https://pkg.go.dev/iter) module, we should provide some easy compatibility and canonicity for handling streams of record batches.
Two new functions: `ReaderFromIter` and `IterFromReader` for converting between the `RecordReader` interface and an iterator of Records and errors. This should make it easy to integrate in various packages without forcing refactors or boilerplate code.
Yes, unit tests are added for them.
No.
> feat(arrow/array): convert RecordReader and iterators

- parquet/file/column_reader.go
- parquet/file/record_reader.go
- parquet/pqarrow/column_readers.go
- parquet/pqarrow/file_reader.go
- parquet/pqarrow/file_reader_test.go
As suggested by https://github.com/apache/arrow-go/issues/278#issuecomment-2741136394 allowing the RecordReader from the `pqarrow` package to also leverage the `SeekToRow` functionality to skip records from a parquet file while respected skipping particular row groups.
Implementing a `SeekToRow` method for `pqarrow.RecordReader` to seek the record reader to a specific row where the next read will start from.
Yes, unit tests are added for this.
Just the new functions.
> feat(parquet/pqarrow): Add SeekToRow for RecordReader

- arrow/ipc/reader.go
- parquet/internal/bmi/bmi.go
I've tried to run a pqarrow based writer/reader on a RaspberryPi. This lead to an almost immediate crash however, due to an unaligned struct member in `ipc.Reader`.
I did not check yet if there are other structs that might have similar issues. It would probably be nice to 
Swapping the struct field order is enough to fix the issue. See also the link in the diff.
Yes, no additional unit tests due to hardware constraints, but my program runs through now.
Less crashing?
I noticed that this will also crash if I do not pass the `noasm` build tag, which is probably also a little unfortunate. This seems to be because the `funclist` in `parquet/internal/bmi/bmi.go` is empty. If you want I can add a default, so the funclist is always initialized with the fallback go implementation, unless …
> fix: go's atomic operations require 64bit alignment in structs on ARM

- arrow/array/builder.go
- arrow/array/float16.go
- arrow/compute/arithmetic_test.go
- arrow/compute/exec/kernel.go
- arrow/compute/executor.go
- arrow/compute/expression.go
- arrow/compute/exprs/exec.go
- arrow/compute/exprs/extension_types.go
- arrow/compute/exprs/types.go
- arrow/compute/internal/kernels/scalar_set_lookup.go
- arrow/compute/internal/kernels/vector_hash.go
- arrow/compute/internal/kernels/vector_selection.go
- arrow/compute/registry.go
- arrow/compute/scalar_set_lookup.go
- arrow/compute/scalar_set_lookup_test.go
- arrow/scalar/append.go
- internal/hashing/xxh3_memo_table.gen.go
- internal/hashing/xxh3_memo_table.gen.go.tmpl
- internal/hashing/xxh3_memo_table.go
- parquet/file/file_writer.go
- parquet/pqarrow/file_writer.go
- parquet/pqarrow/schema.go
Since we use arrow-go for iceberg-go and utilize the compute libraries for filtering, we need to ensure we add support for the minimal number of functions that iceberg requires. 
Implementing the `is_in` function for the function registry, registering it by default, and ensuring we also allow using `is_in` from substrait. 
Yes, unit tests are included.
There shouldn't be any user-facing changes.
> feat(arrow/compute): implement "is_in" function

- parquet/file/file_writer.go
- parquet/pqarrow/file_writer.go
- parquet/pqarrow/schema.go
- parquet/pqarrow/schema_test.go
While implementing things for iceberg-go, I found that an Arrow schema with nested fields (struct/map/list) that contains metadata values for FieldID is not respected when writing a file using `pqarrow`. 
Fixes the propagation of field ids when constructing a Parquet file from an arrow schema that contains nested fields, while also adding a `FileMetadata` function to the FileWriter and `pqarrow.FileWriter` so that you can inspect the metadata of a written file without having to read it back into memory.
Yes
No
> fix(parquet/pqarrow): fix propagation of FieldIds for nested fields

- parquet/file/column_writer.go
- parquet/pqarrow/path_builder.go
- parquet/pqarrow/path_builder_test.go
Related to https://github.com/apache/arrow/issues/38503, it was found in https://github.com/apache/iceberg-go/issues/357 that the Parquet file being written by pqarrow was incompatible with pyarrow in some testing. After some digging I determined the cause. So we should fix this to finally put #38503 to bed
Fixing the computation of definition levels when writing from Arrow data with lists of non-nullable elements. Previously we were basing the `nullableInParent` on whether it was a list or a map, assuming that the element was *always* nullable in a list. This, of course, is incorrect and we need to actually *check* the nullability of the list element to compute the correct definition level. This way we don't produce incongruous levels that are larger than what the max definition level …
> fix(parquet/pqarrow): fix definition levels with non-nullable lists

- parquet/file/column_writer.go
- parquet/file/column_writer_types.gen.go
- parquet/file/column_writer_types.gen.go.tmpl
- parquet/file/file_reader.go
- parquet/file/file_writer.go
- parquet/file/file_writer_test.go
- parquet/file/row_group_writer.go
- parquet/metadata/bloom_filter.go
- parquet/metadata/bloom_filter_reader_test.go
- parquet/writer_properties.go
Support for reading and writing bloom filters to files is important for allowing consumers to skip row groups/columns/etc.
Adding functionality to the Writer and Reader to allow for writing and reading bloom filters from parquet files directly. Adding write properties to control if and how bloom filters get written.
Yes. Unit tests are added.
Only the newly available functions.
> feat(parquet): Write/Read bloom filters from files

- parquet/file/file_reader.go
- parquet/file/row_group_reader.go
Fixes #342 
use `sync.OnceValues` to initialize the row group page index reader on demand, but safely
> fix(parquet/file): restore goroutine safety for reader

- .asf.yaml
We have enabled GitHub discussions on all other repositories for Arrow.
Changes to `.asf.yaml` to enable GitHub discussions.
No relevant.
No
> chore: Enable GitHub discussions on arrow-go repository

- parquet/compress/compress.go
- parquet/compress/compress_test.go
Right now, there is no public API to convert a string like `"ZSTD"` to a compression codec. There is only https://pkg.go.dev/github.com/apache/arrow-go/v18@v18.2.0/parquet/internal/gen-go/parquet#CompressionCodecFromString but that can't be used since it's in an `internal` package.
Adding `UnmarshalText` can be used for applications taking such a string as configuration option. Adding `MarshalText` isn't strictly needed since it overlaps with `String()` but makes sense for symmetry.
Add `UnmarshalText` and `MarshalText` as thin wrappers around the same methods from the internal https://pkg.go.dev/github.com/apache/arrow-go/v18@v18.2.0/parquet/internal/gen-go/parquet#CompressionCodec type.
Yes
Minor new API for `Compression` type
> Compress: add MarshalText and UnmarshalText

- arrow/array/struct.go
- arrow/array/struct_test.go
https://github.com/apache/iceberg-go/issues/398 discovered that the current `NewStructArrayWithFields` fails if any child is marked as non-nullable but has nulls (as would be the case in an optional struct array full of nulls with a required field). So we need to allow constructing such an array.
A new function is created, `NewStructArrayWithFieldsAndNulls` which takes in the top level struct null bitmap, the number of nulls, offset columns and list of fields.
Yes, a unit test was created for it.
The above case that would error, now will no longer error.
> fix(arrow/array): optional struct array with required field

- parquet/internal/gen-go/parquet/parquet.go
- parquet/pqarrow/column_readers.go
- parquet/pqarrow/schema.go
- parquet/pqarrow/schema_test.go
- parquet/pqarrow/variant.go
- parquet/pqarrow/variant_test.go
- parquet/schema/logical_types.go
- parquet/schema/logical_types_test.go
Closes #348 
This is heavily based on https://github.com/apache/arrow/pull/45375 for reference.
Initial implementation of the Variant Logical Type in the Parquet schema package and an arrow extension type to represent it.
This *does not* implement actually encoding or decoding the variant data, nor does it implement actually reading or writing data. To this end, the extension type *is not exposed* or otherwise exported from this package currently so it can only be constructed internally for now until there is a standardized canonical extension representation for it.
Yes, unit tests are added for the changes.
Only the new types and ability to manipulate schemas with Variant annocated fields.
> feat(parquet/schema): initial variant logical type

- parquet/file/column_writer.go
- parquet/file/column_writer_test.go
We saw crash with call stack:
```
error: runtime error: invalid memory address or nil pointer dereference
runtime.gopanic
runtime/panic.go:792
runtime.panicmem
runtime/panic.go:262
runtime.sigpanic
runtime/signal_unix.go:925
github.com/apache/arrow-go/v18/arrow/memory.(*Buffer).Bytes
github.com/apache/arrow-go/v18@v18.2.0/arrow/memory/buffer.go:106
github.com/apache/arrow-go/v18/parquet/file.(*page).Data
github.com/apache/arrow-go/v18@v18.2.0/parquet/file/page_reader.go:90
github.com/apache/arrow-go/v18/parquet/file.(*columnWriter).TotalBytesWritten
github.com/apache/arrow-go/v18@v18.2.0/parquet/file/column_writer.go:203
github.com/apache/arrow-go/v18/parquet/file.(*rowGroupWriter).Close
github.com/apache/arrow-go/v18@v18.2.0/parquet/file/row_group_writer.go:237 …
```
> Fix panic when WriteDataPage fails

- arrow/flight/flightsql/column_metadata.go
- arrow/internal/flight_integration/scenario.go
See https://github.com/apache/arrow/pull/46110
A new column metadata value
No; there seem to be no tests that'd verify that `ColumnMetadata` works; should I add unit tests specifically for the new methods?
Yes, two new methods
> GH-46087: [FlightSQL] Allow returning column remarks in FlightSQL's CommandGetTables

- arrow/cdata/cdata.go
- arrow/cdata/cdata_test.go
- arrow/cdata/cdata_test_framework.go
- arrow/cdata/interface.go
See https://github.com/apache/arrow-go/issues/371
@zeroshade 
A new `ReleaseCArrowArrayStream` function to facilitate triggering the release callback of a `CArrowArrayStream`.
```
$ go test ./arrow/cdata -tags=test -count=1
ok      github.com/apache/arrow-go/v18/arrow/cdata      5.413s
```
Yes, a new function is added.
> feat(arrow/cdata): Add ReleaseCArrowArrayStream function

- parquet/file/file_reader_test.go
- parquet/internal/encoding/delta_bit_packing.go
- parquet/internal/encoding/delta_byte_array.go
This exact test seems to be passing on v17 version. More investigation is needed
After updating from v17 to v18 I noticed a test case failing that was passing before.
This PR contains a test case to reproduce the issue. A reference PR for version v17 can be found here
- https://github.com/apache/arrow/pull/46353
The PR itself just contains the test
> fix: TestDeltaByteArray implementation and fix

- parquet/file/file_reader_test.go
- parquet/pqarrow/column_readers.go
add list_columns.parquet testing. `rr.Next()` is returning true when we've already reached the end of the file. This leads to a panic later on
- Test that proves list_columns.parquet is not working as expected.
- Use known path for partquet_testing if var is not defined. This ensures test can be run as usual but still enables custom locations for parquet_test_data. It also guarantees failure if not run correctly.
That is the goal of the PR
no?
> fix: list_columns.parquet testing

- parquet/pqarrow/file_reader.go
- parquet/pqarrow/file_reader_test.go
Closes #379
Update the `SeekToRow` method of the record reader to parallelize the calls to `SeekToRow` for the columns if the Parallel option is set to true.
Yes, the RecordReader SeekToRow is already tested via unit tests with multiple columns.
There should only be the performance benefit
> feat(parquet/pqarrow): parallelize SeekToRow

- .github/workflows/test.yml
We split js/ in apache/arrow to apache/arrow-js.
Use apache/arrow-js not apache/arrow for JS.
Yes.
No.
Closes #388.
> chore: Use apache/arrow-js for JS in integration test

- parquet/pqarrow/encode_dictionary_test.go
- parquet/pqarrow/schema.go
- parquet/pqarrow/schema_test.go
An issue was found in apache/iceberg-go when attempting to retrieve data from a table containing a List Column that had a struct as the element. It was failing to propagate the element-id for the fields when fetching. I tracked it down to the schema handling here.
Changes the `getNestedFactory` method in pqarrow/schema.go to use `ListOfField` instead of `ListOf` so that it preserves the metadata, i.e. the field id.
Yes, a test has been added to cover this scenario.
Previously this situation would result in a field-id of -1, now users will see the field-id get propagated correctly.
> fix(parquet/pqarrow): Fix propagation of field-ids for Lists

- .github/workflows/test.yml
GitHub is deprecating Windows hosted runners for 2019, see:
- https://github.com/actions/runner-images/issues/12045
We did update on the main Apache Arrow repo already, see:
- https://github.com/apache/arrow/pull/46694
Update the runner version
Yes via CI.
No
Closes: https://github.com/apache/arrow-go/issues/406
> chore: bump Windows GitHub hosted runner to windows-2022

- arrow/decimal/decimal.go
- arrow/extensions/variant.go
- arrow/extensions/variant_test.go
- parquet/variant/builder.go
- parquet/variant/builder_test.go
Next step on the route to fully support reading/writing Variants in Parquet is to support Parsing JSON into variants since we already can marshal to JSON.
Adding a `ParseJSON` function to the `parquet/variant` package.
Yes, unit tests are added.
Just the new functions
> feat(parquet/variant): Parse JSON into variant

- arrow/extensions/variant.go
- parquet/pqarrow/schema.go
- parquet/pqarrow/schema_test.go
Updating the `pqarrow` package to handle the variant extension type when converting between arrow and parquet schemas.
Replacing the TODOs with implementations to handle shredded variant structures in schema conversion.
A unit test is added for shredded variant handling.
Only that this is now supported instead of erroring.
> feat(parquet/pqarrow): Correctly handle Variant types in schema

- go.mod
- go.sum
remove the Replace directive to use the released substrait-go@v4.3.0
> build(deps): update to substrait-go v4.3.0

- arrow/compute/exprs/exec.go
- arrow/compute/exprs/exec_test.go
While #404 fixed support for substrait precision types on inputs, it did not address support for literals that use the Precision types. 
Fixes #446
Fix `literalToDatum` so that it properly supports the precision types for literals.
Yes, a unit test is added.
Just the increased support
> fix(arrow/compute/exprs): fix literalToDatum for precision types

- arrow/array/timestamp.go
- arrow/array/timestamp_test.go
- arrow/avro/testdata/testdata.go
resolves #445
Use `time.RFC3339Nano` for the format to output the time value
Yes
Changes the format of timestamp strings for `ValueStr` and marshalling to JSON to match JSON and Go conventions.
> fix(arrow/array): update timestamp json format

- arrow/array/data.go
- arrow/array/data_test.go
My program crashed with below log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53beb92]
goroutine 294 [running]:
github.com/apache/arrow-go/v18/arrow/array.(*Data).Release(0xc02586a5b0)
/root/go/pkg/mod/github.com/apache/arrow-go/v18@v18.4.0/arrow/array/data.go:150 +0x172
github.com/apache/arrow-go/v18/arrow/array.concat.func1()
/root/go/pkg/mod/github.com/apache/arrow-go/v18@v18.4.0/arrow/array/concat.go:528 +0x9c
github.com/apache/arrow-go/v18/arrow/array.concat({0xc14ae66008, 0x100, 0x100}, {0x83213c0, 0xb026080})
/root/go/pkg/mod/github.com/apache/arrow-go/v18@v18.4.0/arrow/array/concat.go:652 +0x3f7d
github.com/apache/arrow-go/v18/arrow/array.Concatenate({0xc104861908, 0x100, 0x12f}, …
```
> fix(array): add nil checks in Data.Release() for childData

- arrow/array/json_reader.go
- arrow/array/record.go
- arrow/array/table.go
- arrow/array/util.go
- arrow/avro/reader.go
- arrow/cdata/cdata.go
- arrow/cdata/cdata_test.go
- arrow/csv/reader.go
- arrow/flight/flightsql/client.go
- arrow/flight/flightsql/example/sql_batch_reader.go
- arrow/flight/flightsql/example/sqlite_server.go
- arrow/flight/flightsql/example/sqlite_tables_schema_batch_reader.go
- arrow/flight/flightsql/example/type_info.go
- arrow/flight/record_batch_reader.go
- arrow/flight/record_batch_writer.go
- arrow/internal/flight_integration/scenario.go
- arrow/ipc/file_reader.go
- arrow/ipc/file_writer.go
- arrow/ipc/reader.go
- arrow/ipc/writer.go
- parquet/pqarrow/file_reader.go
Rename the Record interface to RecordBatch for clarity, since Record commonly means a single row but this type represents a batch of rows.
In addition, some method names such as NewRecord have been changed to NewRecordBatch, but the old methods still exist as wrappers around the newly named methods to maintain backward compatibility.
The following packages now use RecordBatch instead of Record:
arrow/ipc 
arrow/flight 
arrow/flight/flightsql 
arrow/internal/flight_integration 
arrow/array
In addition:
- Fixed interface compatibility issues in dependent packages (arrow/avro, arrow/csv, arrow/cdata, parquet/pqarrow)
- Updated all Record() methods to call RecordBatch() for consistency
All affected packages build successfully and core tests pass. Some tests requiring external dependencies …
> refactor(arrow): fourth increment of the Record -> RecordBatch migration

- parquet/pqarrow/encode_arrow_test.go
- parquet/pqarrow/encode_dict_compute.go
- parquet/pqarrow/encode_dictionary_test.go
When dictionary encoding is enabled and and repetitions are set to `required`, the `null_count` statistic is negative because `defLevels` is always 0.
This PR sets the null count to 0 if `defLevels - nonNullCount < 0`
Yes. I've added a new test that exposes another bug. I started with the `fullTypeList` variable like [this test](https://github.com/apache/arrow-go/blob/c6ce2ef4e55009a786cf04b3845eba5170c98066/parquet/pqarrow/encode_dictionary_test.go#L43) and discovered that not all types are supported. 
If an unsupported type is encoded as a dictionary, it results in a nasty panic in the typed dictionary encoder because the types don't line up.
Yes, the stats written to parquet files are currently wrong for these sorts of columns. This PR should fix that!
> fix(parquet/pqarrow): Fix null_count column stats

- .github/workflows/rc.yml
- .github/workflows/release.yml
Fixes #496
We should automate release process as much as possible to reduce maintenance cost.
* Add a workflow that is used on release tag such as `v18.4.1`
* It creates a GitHub Release for the release automatically
* Asserts are copied from the GitHub Released of the passed RC
* It also creates a discussion for the release
* It updates the asf-site branch
No...
Yes.
> chore: Automate GitHub Releases creation and site redirect

- arrow/bitutil/bitmap_ops.go
- arrow/bitutil/bitmaps.go
- arrow/bitutil/bitmaps_test.go
- arrow/compute/internal/kernels/scalar_comparisons.go
- arrow/compute/scalar_compare_test.go
fixes https://github.com/apache/arrow-go/issues/493
Add bitxnor operation, utilize bitxnor for boolean equality.
Yes
Boolean equality operations now return correct results. No changes to the public API.
> use xnor for boolean equals function

- arrow/array/dictionary.go
- arrow/array/dictionary_test.go
The underlying hash table is in terms of primitive types (int64/int32/int16, etc.) not the top-level types (arrow.Duration, arrow.Timestamp, etc.) which results in a panic mismatch when appending values. 
fixes #516 
Checking and validating the type when appendValue is called to ensure correct type coercion.
A unit test is added in this change.
A case that previously caused a panic will now be successful.
> fix(arrow/array): fix panic in dictionary builders

- parquet/internal/encoding/byte_array_encoder.go
- parquet/internal/encoding/fixed_len_byte_array_encoder.go
- parquet/internal/encoding/typed_encoder.go
- parquet/internal/encoding/types.go
- parquet/pqarrow/encode_arrow_test.go
- parquet/pqarrow/encode_dict_compute.go
- parquet/pqarrow/encode_dictionary_test.go
fixes #490 
When using `PutDictionary` to write an arrow dictionary array to Parquet directly, we will now normalize the data type to a parquet physical storage type to avoid type problems. e.g. A dictionary with `int8` values will get cast to `int32` values before we process it so that all of the remaining encoding code can continue to be based on the physical storage type. This alleviates panics when using `pqarrow` to write Dictionary arrays.
Yes, the unit tests are updated to include tests for int8/uint8/etc. as dictionary value types.
No, just fixing panics.
> fix(parquet/pqarrow): unsupported dictionary types in pqarrow
